### PR TITLE
Review the project via a pull request

### PR DESCRIPTION
**Pull request by roodjinocherilus**
This pull request is for the code review of my own project

### CODE REVIEW

**Comment by roodjinocherilus** [comment]
Hello Brother! You did a good job with this project so far, but there are a lot of things we need to address.

**Comment by roodjinocherilus** [comment]
1) You did not use a proper flow for the project. You should use the GitHub flow so your main codebase remains stable and safe at all times.

2) There is no linter setup in the repository. Linter is a code analysis tool to help you catch bugs and programming errors. so without a linter,  I am pretty sure, your code has a lot of syntax and stylistic errors.

3) Your Readme is poor in terms of documentation, you should document your review in a way every person coming across your repository know what it is about.

**Comment by Gopxfs** [comment]
> 1. You did not use a proper flow for the project. You should use the GitHub flow so your main codebase remains stable and safe at all times.
> 2. There is no linter setup in the repository. Linter is a code analysis tool to help you catch bugs and programming errors. so without a linter,  I am pretty sure, your code has a lot of syntax and stylistic errors.
> 3. Your Readme is poor in terms of documentation, you should document your review in a way every person coming across your repository know what it is about.

Hello @roodjinocherilus 👋, please notice as requested in the project requirements:
image
You should have at least two separate comments saying what you could improve 😉. It is important that these comments are separated so you can make use of the inline comments, as explained [here](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/give_code_review_basics.md). Inline comments are important to make your review clear and direct while making explicit the piece of code that needs to be updated 😄.

In this case, your point number 3 could be linked to the readme file 😃.

Overall, you did a very good job, well done! You were direct to the point and very polite. Cheers, and keep up the good work!

**Review by Gopxfs — CHANGES_REQUESTED** [review]
# ♻️ STATUS: REQUIRED CHANGES ♻️

## Hi @roodjinocherilus 👋,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights :rocket:
✔️ No linter errors.
✔️ Great code structure. Well done!
✔️ You were clear and polite!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 🗒️  
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Gopxfs in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by roodjinocherilus** [comment]
1. You did not use a proper flow for the project. You should use the GitHub flow so your main codebase remains stable and safe at all times. [Take a look at this article from microverse](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md)

**Comment by roodjinocherilus** [comment]
2- There is no linter setup in the repository. Linter is a code analysis tool to help you catch bugs and programming errors. so without a linter, I am pretty sure, your code has a lot of syntax and stylistic errors. You can learn more about linter,[ here](https://github.com/microverseinc/linters-config)

**Comment by roodjinocherilus** [comment]
4. Your Readme is poor in terms of documentation, you should document your review in a way every person coming across your repository know what it is about. [Here is a readme template from Microverse](https://github.com/microverseinc/readme-template/blob/master/README.md)

**Review by Gopxfs — APPROVED** [review]
# 🟢 STATUS: APPROVED 🟢

## Hello @roodjinocherilus 👋,

Your project is complete! You followed all the requirements, feel free to merge it! 😄
Congratulations! 🎉 



## Highlights
✔️ Linters are passing successfully.
✔️ Implemented all the changes requested by the previous reviewer. Well done!

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by roodjinocherilus** [comment]
> # 🟢 STATUS: APPROVED 🟢
> ## Hello @roodjinocherilus 👋,
> Your project is complete! You followed all the requirements, feel free to merge it! 😄 Congratulations! 🎉
> 
>  [ 68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6358626c6e4b58723242514f61596e546e692f67697068792e676966 ](https://camo.githubusercontent.com/b8aeabd342df3c11e07222f6dd170fb9da9ba447e706d9eab6a5c20adf863d20/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6358626c6e4b58723242514f61596e546e692f67697068792e676966) [ ](https://camo.githubusercontent.com/b8aeabd342df3c11e07222f6dd170fb9da9ba447e706d9eab6a5c20adf863d20/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6358626c6e4b58723242514f61596e546e692f67697068792e676966)
> 
> ## Highlights
> ✔️ Linters are passing successfully. ✔️ Implemented all the changes requested by the previous reviewer. Well done!
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Thank you !

**Pull request merged**
